version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    expose:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
