version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conduit
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
